DROP TABLE IF EXISTS ROUTES;
DROP TABLE IF EXISTS TBL_ROUTE;
 
CREATE TABLE ROUTES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  POINT_A VARCHAR(250) NOT NULL,
  POINT_B VARCHAR(250) NOT NULL,
  DISTANCE INT(11) NOT NULL
);